repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --indent, '2']
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: [--remove]
  - id: check-case-conflict
  - id: mixed-line-ending

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports
    files: ^code/

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.1
  hooks:
  - id: pyupgrade
    args: [--py39-plus]

- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    args: [--in-place, --wrap-summaries=120, --wrap-descriptions=112, --blank]

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs

- repo: https://github.com/bemeurer/beautysh
  rev: v6.2.1
  hooks:
  - id: beautysh

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.20.1
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [--profile, black, --filter-files, --line-length=120]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    args: [--line-length=120]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args: [--max-line-length=120, '--ignore=E203,W503', '--per-file-ignores=_version.py:F401,versioneer.py:F401']

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
    args: [--install-types, --non-interactive, --explicit-package-bases, --namespace-packages, --ignore-missing-imports]
